### ISSUE TITLE
Environment variables not being recognized

### ISSUE THREAD

**Issue by MrOutis** [nickjj/orats#13]
I solved this installing the `dotenv` gem.

I think is a good practice to put `dotenv` in the Gemfile, however, if your intention was to create something _gem-agnostic_ to load environment variables (allowing the user to choose from Figaro or Dotenv), it would be great to add a section in the README indicating that.

So far, so good. Thank you, again, for reducing the boilerplate (and a great documentation to understand the _why's_ configuring the project) :beer:.

**Comment by nickjj** [comment]
Hi,

You don't need the `dotenv` gem.

The Docker Compose file is loading in the `.env` file (which should have all of your custom ENV variables) and it's passing them all to the Rails app when you run it.

**There is 1 caveat**, and that's this line in the `Dockerfile`:
`RUN bundle exec rake RAILS_ENV=production DATABASE_URL=postgresql://user:pass@127.0.0.1/dbname ACTION_CABLE_ALLOWED_REQUEST_ORIGINS=foo,bar SECRET_TOKEN=dummytoken assets:precompile`

Environment variables aren't loaded when the Docker image gets built. If it's something that Rails thinks is mission critical and it happens to be `nil` then you need to put a dummy value there to prevent Rails from complaining.

**Comment by MrOutis** [comment]
ohh, okok, now I see.

I wanted to do `rails secret` for the `SECRET_TOKEN` and I realized that the envs weren't loading.

good to know!

**Comment by nickjj** [comment]
You would need to start up everything with `docker-compose up` and then run:

`docker-compose exec --user "$(id -u):$(id -g)" website rails secret`

- If you're on OSX or Windows you can skip adding the `--user` flag.
