### ISSUE TITLE
deploy on gcp

### ISSUE THREAD

**Issue by Rovel** [nickjj/orats#22]
Hi,

I'm trying to deploy a orats base template on google cloud and I'm getting, some weird errors due to  docker/docker-compose/kubernetes can you provide any material on kubernetes or deploying a docker-compose on gcloud?

Thanks

**Comment by nickjj** [comment]
Hello,

Sorry. That goes beyond the scope of this project. This project helps you build a Dockerized app.

I don't plan to create tutorials/guides on various ways of deploying it. At least not in this repo.
