### ISSUE TITLE
Updating gemfile, but the gem being installed is not changed

### ISSUE THREAD

**Issue by deanfields** [nickjj/orats#26]
Hi,

I am attemting to change my gemfile from:
```
gem 'rspec-rails', '~> 3.6
```
to 
```
gem 'rspec-rails', '~> 3.5', '>= 3.5.2'
```

I have removed everything such as the volumes and the cached images but nothing seems to work.

I am also running 

```
docker-compose up --build
```

Could this be a bug?

**Comment by deanfields** [comment]
I just removed  '>= 3.5.2' from the end and it looks like it's done the trick, apologies my mistake!

**Comment by nickjj** [comment]
When installing new gems `docker-compose up --build` is all you'll ever have to do.

`~> 3.5` will install the latest 3.5.x release.

Typically that's a safe play. If you wanted `3.5.2` exactly you could change it to just `~> 3.5.2`.

**Comment by deanfields** [comment]
Thanks very much for the clarification I completely mis-interpreted the '>= 3.5.2', I didn't realise it would install 3.6! (it's not my day today!) 

I am copying the lines from rubygems  I feel this isn't something they used to do? Or It's just never caused me a problem before!

**Comment by nickjj** [comment]
There is an example of using a gem range in the `Gemfile`.

`gem 'listen', '>= 3.0.5', '< 3.2'`

That will make sure you always get a version in between those 2 ranges.

But in your case, it sounds like you want some variant of `3.5` so `~> 3.5` works perfectly.
