### ISSUE TITLE
Community question: do you think Capybara and Selenium should be included by default?

### ISSUE THREAD

**Issue by nickjj** [nickjj/orats#30]
A Rails 5.1+ application will add these to your `Gemfile` by default:

```ruby
gem 'capybara', '~> 2.13'
gem 'selenium-webdriver'
```
In orats, I've commented them out, and adding them back in is easy enough, but would you like to see these enabled by default?

**Comment by deanfields** [comment]
Yes, it would be cool to see a container set up to run the tests in for efficiency

**Comment by archonic** [comment]
I'd also like to see some conventions for acceptance testing. In my experience cucumber tests have been quite flakey. I believe docker would remove most of the reasons why random failures happen.

**Comment by nickjj** [comment]
These have been enabled in the successor project to orats which is available https://github.com/nickjj/docker-rails-example.
