### ISSUE TITLE
Would Lograge for STDOUT logging be most appropriate?

### ISSUE THREAD

**Issue by jonathanstiansen** [nickjj/orats#32]
This puts the whole log message, or query, on a single line. 

I've used this for docker, since it also works super well with third party logging  software - i.e. easy to parse.

1. Have you used it?
2. Do you think it could be a better default than just basic rails logging with STDOUT?

**Comment by jonathanstiansen** [comment]
For reference: https://github.com/roidrage/lograge

A query would look like this:

`method=GET path=/jobs/833552.json format=json controller=JobsController  action=show status=200 duration=58.33 view=40.43 db=15.26`

**Comment by nickjj** [comment]
I don't like how it strips out information such as view partial rendering times. Not everyone integrates with new relic and other tools to retrieve that missing data.

But if you need to ship your logs somewhere, lograge is one of the better libs. I've worked with it a bit about a year ago.

**Comment by jonathanstiansen** [comment]
Fair enough Nick! I'll close this then.

**Comment by nickjj** [comment]
No problem, thanks a lot for reading and the support through buying any courses.
