### ISSUE TITLE
Created a new project and psql connection fails

### ISSUE THREAD

**Issue by deanfields** [nickjj/orats#35]
The DATABASE_URL within the .env file is using the role/user based on the project name. The POSTGRES_USER seems to be set as testo (which seems to be the actual user that has been created for the database)

This is causing a connection error unless the DATABASE_URL is changed to have the user as testo.

**Comment by nickjj** [comment]
Well, that's embarrassing. I grabbed that out of my test project and it crept its way into the repo.

I just pushed `v5.2.1` which sets the proper `POSTGRES_USER`.

You can fix this without generating a new app by running `docker-compose down -v` and then manually setting the value if you want. It should be the same name as whatever the username is set to in `DATABASE_URL` (ie. your app name).
