### ISSUE TITLE
Add additional templates

### ISSUE THREAD

**Issue by deanfields** [nickjj/orats#36]
I think bootstrap and other style type gems (maybe font-awesome) should be removed from the base, and a couple of other templates added such as:

- bootstrap
- Foundation
- React
- API only (would be great)

**Comment by nickjj** [comment]
Hi,

Thanks for the idea. Unfortunately these extra templates won't make it in.

It becomes a bit too cumbersome to try and support all of those combinations in this project. Perhaps such things could be created with individual application templates maintained by folks who use those tech choices.
