### ISSUE TITLE
Webpacker support

### ISSUE THREAD

**Issue by archonic** [nickjj/orats#38]
I've got webpacker working nicely on Docker/Docker Compose.
https://github.com/archonic/webpacker-docker

The only non-obvious solution I needed was setting `WEBPACKER_DEV_SERVER_HOST=webpack` in the env file, where `webpack` is the name of the webpack service. That gets Rails to be aware of the already running webpack-dev-server and stop compiling already compiled files on refresh.

I don't really have an opinion on including this in orats, but I figure people might want to know how it could be done.

**Comment by nickjj** [comment]
Thanks for providing an example project to work off of.

Switching to webpacker isn't something I've done yet so I'm reluctant to add it to the project right away but I'm sure others will appreciate seeing how to tie it in.

**Comment by nickjj** [comment]
If anyone is curious, https://github.com/nickjj/docker-rails-example is now up to date with Webpacker support. It's the successor project to orats.
