### ISSUE TITLE
Error with initializer file content_security_policy 

### ISSUE THREAD

**Issue by deanfields** [nickjj/orats#39]
I am getting this error on a new project build:

```app/config/initializers/content_security_policy.rb:20:in `<top (required)>': undefined local variable or method `_r' for main:Object (NameError)```

**Comment by nickjj** [comment]
Oops, that was a last minute rubocop failure.

How do things work if you replace: `lambda(_r) {`

With this: `lambda(_) {`

**Comment by deanfields** [comment]
Working now - Thanks
