### ISSUE TITLE
Base App Template produces an error

### ISSUE THREAD

**Issue by DomAmato** [nickjj/orats#43]
I used the batch script from the readme to clone in and create a new app template but when I run docker compose the website, sidekiq, and cable images produces this error:
`/app/config/initializers/timeout.rb:1:in '<top (required)>': undefined method 'timeout=' for Rack::Timeout:Class (NoMethodError)`

It seems this method was dropped in the newer version of rack-timeout https://github.com/heroku/rack-timeout/issues/130

Not sure what method you would prefer but as it stands it seems either rack-timeout needs to be downgraded to 0.4.* or the offending code updated for the newer syntax

**Comment by russdavisdotcom** [comment]
An issue is great, a PR would be fantastic.

**Comment by nickjj** [comment]
I'm thinking we should delete `initializers/timeout.rb` and then rename `REQUEST_TIMEOUT` in the `.env` file to be `RACK_TIMEOUT_SERVICE_TIMEOUT`. According to their docs, environment variables can be used directly to configure everything which is referenced at https://github.com/heroku/rack-timeout#configuring.
