### ISSUE TITLE
undefined method `timeout=' for Rack::Timeout:Class (NoMethodError)

### ISSUE THREAD

**Issue by deanfields** [nickjj/orats#47]
Hi, I have just installed the newest version of orats, and used it.

I am getting an error with timeout (initializers/timeout.rb) complaining about no method error

**Comment by nickjj** [comment]
Hi,

Did you update the rack timeout gem manually?

A PR was merged recently to fix this.

1. Delete `initializers/timeout.rb`
2. In `.env` rename `REQUEST_TIMEOUT` to `RACK_TIMEOUT_SERVICE_TIMEOUT`.

**Comment by deanfields** [comment]
The gem was set to 4 still, so I have gone ahead and done the changes that were in the recent updates - which is working now. I thought this was in the new version?

**Comment by nickjj** [comment]
It was on master, but not included in a proper release.

I'll release a fix today.
