### ISSUE TITLE
Is this project still actively maintained?

### ISSUE THREAD

**Issue by russdavisdotcom** [nickjj/orats#50]
Seeing the last commit was September 2018, is this project still actively maintained?

**Comment by nickjj** [comment]
Hi,

I haven't really maintained this project in quite some time.

My thought process was to archive this repo, but before doing that I want to first ship a less opinionated Dockerized Rails example app, and then anyone can go from there adding their own app specific requirements to it.

**Comment by nickjj** [comment]
That new repo is now available at https://github.com/nickjj/docker-rails-example.

It's up to date and will continue to be maintained while orats will be archived.
